### PR TITLE
Support python 3.7

### PR DESCRIPTION
**Pull request by aviralpandey**
Many things, most notably Google Colab still only support python3.7. This merge will allow HDL21 to support python3.7

### CODE REVIEW

**Comment by dan-fritchman** [comment]
Terrific, thanks for putting this together.  

One paired thing to change: testing with Python v3.7. 
That *should* just be another item in this list here: 
https://github.com/dan-fritchman/Hdl21/blob/44e3909880df5542de894eecd10396bb5f702bea/.github/workflows/test.yaml#L24

I can add that, or go for it if you have a chance.

**Comment by dan-fritchman** [comment]
(And while those tests are currently failing - it all appears to be in the formatting stage, which I broke, not you.)

**Comment by aviralpandey** [comment]
Nothing more from me

**Comment by dan-fritchman** [comment]
Alright I'll roll in the tests/ formatting and get this merged right quick.

**Pull request merged**
